import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import './globals.css'

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "UnClash - Language of Peace",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={nunito.className}>
          {children}
          <UserButton/>
        </body>
      </html>
    </ClerkProvider>
  )
}